name: basic-app

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map host port 3000 to container port 3000
    environment:
      # Example: pass backend environment variables
      NODE_ENV: production
      FRONTEND_URL: http://localhost # Or your frontend's accessible URL
    depends_on:
      - database # Ensure database starts before backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map host port 80 to container port 80
    depends_on:
      - backend # Ensure backend starts before frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
