name: basic-app

services:
  database:
    image: pgvector/pgvector:pg16-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advanced_RAG
    ports:
      - "5433:5432" # Map host port 5432 to container port 5432
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map host port 800 to container port 8000
    env_file:
      - ./backend/.env
    depends_on:
      - database # Ensure database starts before backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Map host port 5173 to container port 80
    depends_on:
      - backend # Ensure backend starts before frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
